version: '3'
services:
  fusuma:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    image: ${PROJECT_NAME}-image
    container_name: ${PROJECT_NAME}-container
    volumes:
      - .:/app
      - ~/.config/fusuma:/home/fusuma/.config/fusuma
    environment:
      - FUSUMA_PORT=${FUSUMA_PORT}
    ports:
      - "${FUSUMA_PORT}:${FUSUMA_PORT}"
    user: "${USER_ID}:${GROUP_ID}"
    env_file:
      - .env